### ISSUE TITLE
Cell outputs disappear in Colab

### ISSUE THREAD

**Issue by yutongy98** [hasanirtiza/Pedestron#128]
Hi, thanks for the great paper and repo! When I ran the train code in Colab, I found the cell outputs for train in Colab are disappear as below: 
![image](https://user-images.githubusercontent.com/44315711/149618998-e323ed0b-ef51-4340-b1c0-6db8261c6b85.jpeg)
Until now the code is running about 1h but still no outputs displayed, did I miss something? Any suggestions will be appropriated, Thanks!

**Comment by hasanirtiza** [comment]
I have never tried to launch Pedestron training script using Colab.
Couple of considerations, why are you running your script like `conda run python` instead of simply `python tools/train.py`.(I am not a colab user, so potentially it could be my bad.)
Secondly, did you try to run simply from the terminal, just to be sure.

**Comment by yutongy98** [comment]
Thanks for your reply! I followed this [PedestronColab.ipynb](https://github.com/hasanirtiza/Pedestron/blob/master/colab/PedestronColab.ipynb) that creates a Conda environment to set up the environment for Pedestron. And I will try to run the script from the terminal later : ) Thanks for your suggestions!
