### ISSUE TITLE
Do Citypersons and ECP datasets contain instance masks?

### ISSUE THREAD

**Issue by cpsxhao** [hasanirtiza/Pedestron#13]
Hi, thank you for your great work! I'm new to pedestrian detection, and I looked through the annotation files of Citypersons and ECP datasets but didn't find the annotations of instance masks. So do these datasets contain instance masks, and how do you train Mask RCNNs on these datasets?

Thanks in advance!

**Comment by hasanirtiza** [comment]
Good question, So CityPersons dataset does contain instance level masks, since its a subset of Cityscapes dataset, you can check on the webpage, that every corresponding rgb image has a labelled image(segmentation mask) as well. 
However, in our training we generate masks on the fly from the bounding boxes i-e we take all the region inside a bounding box as a mask (from our experience we have noticed that this strategy brings slight improvement in performances). You can have a quick look at the function [_parse_ann_info()](https://github.com/hasanirtiza/Pedestron/blob/d9e31067350463f70c8fa38474c2872784a0625d/mmdet/datasets/coco.py#L59).  So to sum up, Pedestron does not expect that your dataset also has a segmentation level annotation nor it uses it. It generates from the box as stated above.

**Comment by cpsxhao** [comment]
I get it. Thank you for your kind response! This helps me a lot!
