### ISSUE TITLE
Update instruction for 2023

### ISSUE THREAD

**Issue by phuvinhnguyen** [hasanirtiza/Pedestron#165]
**Describe the feature**

I have tried to setup SOLIDER (using Pedestron environment) for my personal project by following the instruction (and try to setup the same environment) but still, cannot setup for many reasons (conflict, missing package, ...). Could you guys provide a new install script, plz ?

Thanks.

**Comment by hasanirtiza** [comment]
Yes, it a problem. Unfortunately, we all have moved out of IIAI and working on other topics and unfortunately could not maintain Pedestron due to our schedule. However, did you try to have a look at this [PR](https://github.com/hasanirtiza/Pedestron/pull/150). It tries to install Pedestron using latest packages. Otherwise, you can also try our Swin - Transformer (that is a bit more recent).
