### ISSUE TITLE
Running Cascade Mask RNN with Mobilenet backbone

### ISSUE THREAD

**Issue by Kyanite123** [hasanirtiza/Pedestron#21]
Hi Hasan!

Thank you for publishing your amazing work and helping the CV community!

I've run the demo.py script on Cascade Mask RCNN (HRNet backbone) using the cascade_hrnet.py configuration and the model you uploaded (epoch_5.pth.stu) and it worked great!

I also want to run the model with the mobilenet backbone thus used the cascade_mobilenet.py configuration with the model named epoch_16.pth.stu. 

The demo seems to run without any exceptions but the detector does not result in any detections (the resulting images are created without detections). 

Do you have an idea why? 

Many thanks,
Kyanite

**Comment by hasanirtiza** [comment]
Not really, I just ran the config now and it worked fine with Mobilenet as well (There were detections on the demo images see below).
I just ran this command:
`python tools/demo.py configs/elephant/cityperson/cascade_mobilenet.py ./models_pretrained/epoch_16.pth.stu demo/ result_demo/` 

Just double check everything, since you could run demo with other backbone, probably it is not down to installation.

![image](https://user-images.githubusercontent.com/22005154/81509615-e515cd00-931c-11ea-8653-44fa88334e46.png)

**Comment by Kyanite123** [comment]
Hi, 

Sorry for the trouble... It seems to work for me also with this command!

BTW what training regime did you use for this model?
Pre training on Wider pedestrian and fine tuning on Cityscapes?

Thanks!

**Comment by hasanirtiza** [comment]
Yes.
