### ISSUE TITLE
wider pedestrian 2019 dataset

### ISSUE THREAD

**Issue by meixitu** [hasanirtiza/Pedestron#4]
Hi @hasanirtiza ,
    Thanks for your nice work.
    In your paper,  you said the wider pedestrian 2019 dataset can be accessed.
![image](https://user-images.githubusercontent.com/32910309/78722565-9a003880-78de-11ea-9a53-04b1e85c1c02.png)

But I visited this website, I can't find how to download this dataset
Could you give me an clue?

Thanks
meixitu

**Comment by hasanirtiza** [comment]
You need to do the following things in order to download the data:
1)  Visit the mentioned website in the paper. Click on the "Participate" tab and click Sign In. There you have an option to sign up, do the sign up if applicable. 
2) After signing up, confirm your email and again visit the "Participate" tab on the website, you will be ask to register yourself. Click on the register button and you would see "Get Data". You should be able to download the data. See attached below.
![Sample_git](https://user-images.githubusercontent.com/22005154/78746578-535f1c80-7978-11ea-9dda-1cfd0d4fd3cb.png)

**Comment by meixitu** [comment]
@hasanirtiza 

    Great, I got it.
    you really help me a lot.

Thanks
Meixitu
