### ISSUE TITLE
can you share the dataset of eurocity person ?

### ISSUE THREAD

**Issue by tangsipeng** [hasanirtiza/Pedestron#48]
can you share the dataset of eurocity person ?

**Comment by hasanirtiza** [comment]
What do you mean by "can you share" ? We have already shared the processed annotations for EuroCity Persons (see [Datasets-PreProcessing.md](https://github.com/hasanirtiza/Pedestron/blob/master/Datasets-PreProcessing.md)). If you meant, sharing the images of EuroCity Persons, that we cannot do, because you need to signup on EuroCity Persons website and perhaps agree to terms and condition, which you should do individually.
