### ISSUE TITLE
Question about Caltech dataset

### ISSUE THREAD

**Issue by zsyawn** [hasanirtiza/Pedestron#5]
Hello Doctor,  I have a question to ask you, when evaluating the Caltech dataset, you are using the Caltech new annotaions provided by Shanshan Zhang, The format is .txt, and the caltech matlab evalutation tool  uses the original annotations and the format is .vbb, so how can I use this new annotation for Evaluation? I need your help, thank you very much!

**Comment by hasanirtiza** [comment]
Yes, we use the new annotations for training. We have added the details on how to evaluate on Caltech along with the Matlab evaluation code [here](https://github.com/hasanirtiza/Pedestron/blob/master/Datasets-PreProcessing.md). In the evaluation code, for the reasonable setting, you do not require annotations for the test set, as they are already contained in the package. Follow the instructions in [Datasets-PreProcessing.md](https://github.com/hasanirtiza/Pedestron/blob/master/Datasets-PreProcessing.md).

**Comment by zsyawn** [comment]
@hasanirtiza For caltech datasets，how to evalute the results on ALL set and Heavy Occlusion set? We only have one ground truth file named gt-Reasonable.mat in Eval_caltech.

**Comment by hasanirtiza** [comment]
You can generate all gt-files from the annotations of Caltech. Nonetheless, we have added now `gt-Reasonable, gt-Occ=heavy` and `gt-All` in the repo. We have also updated `gt-Reasonable` (new annotations by Shanshan). By default, `dbEval.m` will evaluate on reasonable subset. In order to evaluate any other subset, on line 52 of `dbEval.m` you need to add this line to evaluate say on occ=heavy :
`exps = exps(9);`

**Comment by zsyawn** [comment]
Thank you very much for your answer, it is very helpful to me
