### ISSUE TITLE
can't build project. 

### ISSUE THREAD

**Issue by Sjoerdtvanvliet** [hasanirtiza/Pedestron#59]
I go the following error running the sudo python3 setup.py develop command:

File "/usr/lib/python3.6/distutils/command/build_ext.py", line 362, in check_extensions_list
    "each element of 'ext_modules' option must be an "
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple",)

trying the other command:
Given no hashes to check 0 links for project 'opencv-python': discarding no candidates
ERROR: Could not find a version that satisfies the requirement opencv-python>=3 (from mmcv>=0.2.6->mmdet==0.6.0+ebd48b8) (from versions: none)
ERROR: No matching distribution found for opencv-python>=3 (from mmcv>=0.2.6->mmdet==0.6.0+ebd48b8)
Exception information:

Is there any way this can be solved, been banging my head for this for 2 days already. Got python 3.6.9 and I have opencv 3.4 installed on my Ubunty 18.04, but it does not seem to detect it. Is there anyway this can be solved?

**Comment by hasanirtiza** [comment]
I think we have faced somewhat similar issue(after up-gradation of our gpus and CUDA) few days ago and it is quite annoying. Straight away couple of things: 
1) Your CUDA version ? 
2) Your numpy version as well? Since Pedestron uses older version, when you try to install opencv, it supersedes your previous numpy version and sometimes messes up the installation. Moreover, opencv-python headless solved the problem in our case.

In anyways, have a look at this [.yml](https://drive.google.com/file/d/1xDSf6tApcltvGrxSHvEWT0vWYrXA3Thb/view?usp=sharing) file and try to create a conda environment with .yml file 

`conda env create -f Pedestron_Legacy.yml`

See if you can install it and run the demo.

**Comment by uniyushu** [comment]
Thanks for response. I fix this by @yuanvq's anwser.
![image](https://user-images.githubusercontent.com/20262193/90859362-ac28d200-e3ba-11ea-9d4f-418888e9d0c1.png)
and Ignore the UserWarning.
`import warnings
warnings.filterwarnings("ignore", category=UserWarning)`

**Comment by And1210** [comment]
Could you upload the yml file again? The link seems to be broken and I am having the same issue.
