### ISSUE TITLE
RetinaNet on the CityPersons dataset

### ISSUE THREAD

**Issue by msha096** [hasanirtiza/Pedestron#65]
Hi there,

I read the config file from config/elephant/cityperson/retinanet_ResNeXt101.py and I found in the model setting....bbox head dict:  num_classes = 81. Why it is 81? What will be the results if we change it to 2 because we are applying it on the Citypersons dataset?

Another general question, I am using an Nvidia 1080 Ti GPU, with 11G memory. What can I do to train this model locally? I have changed the imgs_per_gpu to 1, device_ids = range(1).

How can I change the backbone to the ResNet-50?

Really appreciate your work and your help!

**Comment by hasanirtiza** [comment]
Hi,
Yes, you have read correctly the num_classes = 81, they are since COCO is with 81 classes. You can change it to two, I do not expect a drastic performance difference. However, you can try it.

 Finally regarding potential memory issue, if reducing batchsize does not solve your issue, I guess then your only option is reducing the image resolution (may be 1000 x 500 or something that works for you keeping the aspect ratio).  

You can change the backbone to ResNet-50 or another backbone you want by changing the backbone in the `config` file. For example, a `config` file for [ResNet-50 is this one](https://github.com/hasanirtiza/Pedestron/blob/master/configs/retinanet_r50_fpn_1x.py), use this instead, or see how to 
change backbone.

**Comment by msha096** [comment]
> Hi,
> Yes, you have read correctly the num_classes = 81, they are since COCO is with 81 classes. You can change it to two, I do not expect a drastic performance difference. However, you can try it.
> 
> Use this config file instead. Finally regarding potential memory issue, if reducing batchsize does not solve your issue, I guess then your only option is reducing the image resolution (may be 1000 x 500 or something that works for you keeping the aspect ratio).
> 
> You can change the backbone to ResNet-50 or another backbone you want by changing the backbone in the `config` file. For example, a `config` file for [ResNet-50 is this one](https://github.com/hasanirtiza/Pedestron/blob/master/configs/retinanet_r50_fpn_1x.py), use this instead, or see how to
> change backbone.

Thanks for your reply!!!!
