### ISSUE TITLE
Assertion Error : Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by iotMice** [hasanirtiza/Pedestron#7]
I am trying to compile the setup file for the last 3 days but didn't get success yet.

I am using Ubuntu 18.04 in Virtual Box. I have a windows machine without GPU.
In Ubuntu, I have installed pytroch for CPU version.
I have also installed Cuda toolkit so that I can have nvcc Compiler. Though I haven't installed gpu driver as I don't have any GPU in the machine.

Please help me to figure this out.

Thanks and Regards

**Comment by hasanirtiza** [comment]
The error message you have posted is about no GPU on the machine and trying to use some CUDA enabled/required elements, for example some past issues that might be useful such as [1](https://discuss.pytorch.org/t/assertionerror-torch-not-compiled-with-cuda-enabled/4614) and [2](). 

Since, Pedestron is built using MMDetection framework (it requires GPU). We have not released or tested a CPU-only version of Pedestron (even for the inference). I am afraid in the current setup, Pedestron expects that you have a GPU. May be you can look at the this [issue](https://github.com/open-mmlab/mmdetection/pull/2385) or [this](https://github.com/open-mmlab/mmdetection/pull/2385) and see if you can compile a CPU-only version.
