### ISSUE TITLE
Update to the latest version of mmdet

### ISSUE THREAD

**Issue by shardulparab97** [hasanirtiza/Pedestron#80]
With many changes incorporated in the newer version of mmdet, would like to request to port the models and configs to the newer version, so that it will be easier to carry on newer research.

No doubt, pedestron is an amazing library and it would be really great if a update is up in the works! :)

Thanks!

**Comment by hasanirtiza** [comment]
#23 
To further update, we do plan to update as mentioned previously, since currently we are surrounded by deadlines, I do not see it happening in near future. As always, community support is most welcome. By the way, it is not drastically different the newer configs, if you are in a hurry, it should be a relatively easier task to adapt to the newer versions. Nonetheless, we will try to update it to the latest version at some point in future.
