### ISSUE TITLE
Questions regarding the paper.

### ISSUE THREAD

**Issue by vobecant** [hasanirtiza/Pedestron#86]
Hello,

first of all, let me thank you for this nice repository.
I have a few questions regarding the paper and the differences in the results in this repository.

1) Are the backbones (e.g., HRNet) somehow pre-trained, or is everything trained from scratch? The same question holds for the detectors - are they somehow initialized from models pre-trained on COCO or other datasets before you use them?

2) Why is the result for ECP->ECP using Cascade RCNN different in Table 7 and table 1?

3) Why are the results for detection on ECP reported in Github repo much better than those presented in the paper? What is it caused by?

Thank you very much for your response.

**Comment by hasanirtiza** [comment]
Hello,

1. Backbones are the standard ImageNet pre-trained for all models as in `mmdetection` framework, you can also try to train them from scratch(may take longer). I am not sure what do you exactly mean by initializing a detector from pre-trained COCO model ?
2. `Table 1` is about dataset statistics in the paper, perhaps you mean `Table 4` ? The difference is the training set (look at training column), in ` Table 7`, we train it on `CrowdHuman or WiderPerson` and Test it on `ECP`.

3. Some models released here (not in the paper) are better, since they have been trained on different sources and then fine-tune on the target set (read sec 5.4 of the paper, although in the paper we do not fine-tune on the target set but the general principal is same). Whereas in the paper, to be fair with other approaches this has not been done.

**Comment by vobecant** [comment]
Hi,

2) Sorry for the confusion, I meant `Table 4` and `Table 6`.
3) Can you please share also the models that were used for the results in the paper?

Thanks!

**Comment by hasanirtiza** [comment]
You can generate all the results in the paper from the provided configs in this repo. We plan to release some more models, but will take sometime. Is there any particular model that you want (specific row of a table) ?
